let changeMe = true;
console.log(changeMe);
changeMe = false;
console.log(changeMe);
const entree = 'Enchiladas';
console.log(entree);
var myName = "Gosia";
var myCity = "Krakow";
console.log(`My name is ${myName}. My favorite city is ${myCity}.`);
let newVariable = 'Playing around with typeof.';
console.log(typeof newVariable);